### ISSUE TITLE
hi 扫描的时候 只能拿到本地ip  请问有别的参数来获取整个局域网下的ip吗？

### ISSUE THREAD

**Issue by Linuxlovers** [timest/goscan#12]
./goscan -I eth0
INFO[0000] 本机ip:192.168.1.201                           
INFO[0000] 内网IP范围:192.168.1.0 --- 192.168.1.255         
192.168.1.201   00:04:4b:df:40:08 miivii-tegra     

能加下QQ咨询下
823129275

**Comment by timest** [comment]
ok
