### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by gyje** [timest/goscan#5]
![error](https://user-images.githubusercontent.com/16876086/32403123-8ddfe2ec-c16d-11e7-8d79-2187de8aece0.png)

**Comment by linux-mac** [comment]
根本就运行不起来啊

**Comment by xwjdsh** [comment]
使用`go build` 或者 `go run *.go`命令。

**Comment by igo9go** [comment]
直接执行 `go build` 不要带后面的文件
